service: lambda-environments

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "qa"}
  environment:
    ${file(./config/env.${self:provider.stage}.json)}
  iamRoleStatements:
    ${file(./config/serverless/db.iam.role.yml)}

custom:
  schedulerRate: rate(1 minute)
  enabled: true
  tableName: ${self:provider.environment.DBTableName}
  dbWriteCapacityUnits: ${self:provider.environment.DBWriteCapacityUnits}
  dbReadCapacityUnits: ${self:provider.environment.DBReadCapacityUnits}

resources:
  Resources:
    ${file(./config/serverless/resources/dynamo.hero.table.yml)}

functions:
  commit-message-scheduler:
    handler: handler.scheduler
    events:
      - schedule:
          rate: ${self:custom.schedulerRate}
          name: schedule-commit-message-${self:provider.stage}
          description: get commit messages each minute
          enabled: ${self:custom.enabled}
